### ISSUE TITLE
Adding TimSort to Boost.Sort

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [timsort/cpp-TimSort#17]
Hello.

I want to add your TimSort's implementation to Boost.Sort library. Can you change license to Boost? Or can i copy your source, rework it in some way (add new constructors, etc. ), change license from MIT to Boost, add your name to authors and send it to Boost.Sort?

Thanks.

**Comment by gfx** [comment]
Thank you for the request. The second option. Feel free to copy it, modify it, and redistribute it with my name under the Boost license.

**Comment by Morwenn** [comment]
@ZaMaZaN4iK Hi, I know that the project has been halted on the Boost side for a while, it had to do about reviews not being performed IIRC.

Anyway, I am now maintaining this project and there will be a few modifications in the days to come. I just wanted to say that you can use any of the modifications I did or I'm about to do and relicense them under the Boost license too. Since you already have Goro's approval for the rest, you should still be able to use all the updated code the Boost license without any issue :)

**Comment by Morwenn** [comment]
I'm closing this issue since the integration is already tracked in boostorg/sort#12.
