### ISSUE TITLE
Recruiting new maintainers

### ISSUE THREAD

**Issue by gfx** [timsort/cpp-TimSort#28]
Because I am not using C++ in production anymore, I'd like to transfer this project to another organization with new maintainers.

However, there're security incidents these days in which attackers inject malware to modules by new maintainers:

* https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

So I'd like to review the org to be transferred carefully, so please tell me the details.

**Comment by Morwenn** [comment]
I don't feel like taking big decisions about the design of the code, I can probably help with basic maintenance tasks since I've already been maintaining a fork of you project for years in one of my libraries.

I guess that no matter what is proposed the goal is - obviously - to keep the timsort algorithm structure without inventing too many new things, to make sure that it is still compatible with C++03, to make sure that the tests pass and that the benchmarks still give good results?

**Comment by gfx** [comment]
@Morwenn Thanks for replying this. I don't think keeping C++03 compatibility because it is too old spec. I think tagging "cpp03-stable", for example, is enough if you upgrade the C++ spec.

And yes, you looks like to have a bunch of C++ libraries already, so it's awesome if you get a maintainer of this library.

So, which do you prefer? (1) transferring it to your account (2) creating an org for this repo and making both I and you as owners.

**Comment by Morwenn** [comment]
Hum, keeping a C++03 branch and taking advantage of newer features in another branch does seem like a sensible option, it's true :)

If it's fine with you I would rather have option (2), creating an org, which would easily allow to add other maintainers if it is needed again someday; that way to also get to intervene if something happens or if I ever disappear for some reason.

**Comment by gfx** [comment]
Cool. I have no idea about tooling, so feel free to change it!

And now this issue is solved!

**Comment by Morwenn** [comment]
I'm currently still a member and not an owner though.

**Comment by gfx** [comment]
@Morwenn Oops.  Changed you to an owner!
