### ISSUE TITLE
Incorrect minRunLength() computing minRun to be too small

### ISSUE THREAD

**Issue by weeyizhi** [timsort/cpp-TimSort#33]
The [following line](https://github.com/timsort/cpp-TimSort/blob/298928ce37e2954956320e764a862b9b1dbc51a7/include/gfx/timsort.hpp#L174) seems incorrect.

Since MIN_MERGE is 32, the loop would end with n containing the 5 most significant bits instead of 6 most significant bits.
Therefore, the function would return [0, 32], which is less than what Python is doing [here](https://github.com/python/cpython/blob/a42759351bff7b07fa8bf2cece0088f8539721d1/Objects/listobject.c#L1983)

The Python detailed description of Timsort in the readme [here](http://svn.python.org/projects/python/trunk/Objects/listsort.txt) also corresponds to returning a size of [32, 64] when possible.

**Comment by Morwenn** [comment]
Indeed, CPython seems to have `MIN_MERGE = 64` and it's not a late addition or fix since it was already the case when this project was started in 2011. If there is a reason for the difference I don't know what it is: the value in this C++ project has been 32 since the initial commit so there isn't any specific commit explaining it. Only @gfx might know why.

I'm going to change it and run all the tests I have to check whether everything still works. If there isn't any obvious issue I will change it to 64. Thanks for the catch.

**Comment by gfx** [comment]
Oh, I don't remember the why. Please fix it.

**Comment by weeyizhi** [comment]
> Indeed, CPython seems to have `MIN_MERGE = 64` ...
`MIN_MERGE` seems to mean "the minimum size at which I will start doing merging". Also, it is also used [here](https://github.com/timsort/cpp-TimSort/blob/298928ce37e2954956320e764a862b9b1dbc51a7/include/gfx/timsort.hpp#L642).

So, I wouldn't change `MIN_MERGE` to 64. On the contrary, I would change [this line](https://github.com/timsort/cpp-TimSort/blob/298928ce37e2954956320e764a862b9b1dbc51a7/include/gfx/timsort.hpp#L174) to `while (n >= 2*MIN_MERGE) {`.
This would ensure that the name `MIN_MERGE` is accurate, and we do merging at sizes of range [32, 64] when there are enough elements left to "top-up" our runs to said sizes. What do you think?

Btw, thanks for maintaining this repo (and many others).

**Comment by Morwenn** [comment]
You're right once again, I applied your proposed resolution, thanks :)

Thank you Goro too for the heads up!
